### ISSUE TITLE
Age Calculator Error Fix

### ISSUE THREAD

**Issue by Bernardopog** [cristianccgg/Age-calculator-app-main#1]
Hello again Cristian, I'm Bernardo, I commented in your post in frontend mentor. Here's the way I fixed your JavaScript. Here's a link to my github with your project modified. I ask you to compare both codes so you can understand what I did.

[Repository](https://github.com/R3ygoski/cristian-age-calculator-app)
[Live Server](https://r3ygoski.github.io/cristian-age-calculator-app/)

If I was of help, please consider marking my answer as helpful on the Frontend Mentor as it helps me a lot.
And if there's some doubt about my code, or anything else, please, comment here our in Frontend Mentor, I will try to answer when I can.

**Comment by cristianccgg** [comment]
> Hello again Cristian, I'm Bernardo, I commented in your post in frontend mentor. Here's the way I fixed your JavaScript. Here's a link to my github with your project modified. I ask you to compare both codes so you can understand what I did.
> 
> [Repository](https://github.com/R3ygoski/cristian-age-calculator-app) [Live Server](https://r3ygoski.github.io/cristian-age-calculator-app/)
> 
> If I was of help, please consider marking my answer as helpful on the Frontend Mentor as it helps me a lot. And if there's some doubt about my code, or anything else, please, comment here our in Frontend Mentor, I will try to answer when I can.

It was nice and helpful. For some reason I thought that was just an icon and not a button. Thank you so much!
